# 坑

为了验证在未设置读取超时时间时，直接调用Conn.Read是阻塞还是立即返回。根据对读取TCP链接数据代码的分析，预期是阻塞。写了一段代码来验证，结果掉坑里了

代码如下:

~~~go
package main

import (
	"fmt"
	"net"
)

func main() {
	runServer()
}

func runServer() {
	l, err := net.Listen("tcp", ":8080")
	if err != nil {
		panic(err.Error())
	}
	defer l.Close()
	for {
	c, err := l.Accept()
	if err != nil {
		panic(err.Error())
	}
	go handleConn(c)
	}
}

func handleConn(c net.Conn) {
	defer c.Close()
	buf := make([]byte, 0, 1024)
	for {
		n, err := c.Read(buf)
		if err != nil {
			fmt.Printf("handleConn err:%s\n", err.Error())
			return
		}
		if n > 0 {
			fmt.Printf("data:%s\n", string(buf[:n]))
			return
		}
		fmt.Printf("n:%d nodata err:%v\n", n, err)
	}
}
~~~

运行结果如下,即一直在输出:

~~~
n:0 nodata err:nil
n:0 nodata err:nil
n:0 nodata err:nil
...
~~~

按照自己的预期，在没有数据可读的情况下，应该一直阻塞。开始有点怀疑自己分析代码得出的结论。又看了一遍读取数据部分的代码，发现在netFD.Read这个函数的第6行 if len(p) == 0

~~~go
func (fd *netFD) Read(p []byte) (n int, err error) {
	if err := fd.readLock(); err != nil {
		return 0, err
	}
	defer fd.readUnlock()
	if len(p) == 0 {
		// If the caller wanted a zero byte read, return immediately
		// without trying. (But after acquiring the readLock.) Otherwise
		// syscall.Read returns 0, nil and eofError turns that into
		// io.EOF.
		// TODO(bradfitz): make it wait for readability? (Issue 15735)
		return 0, nil
	}
	if err := fd.pd.prepareRead(); err != nil {
		return 0, err
	}
	if fd.isStream && len(p) > 1<<30 {
		p = p[:1<<30]
	}
	for {
		n, err = syscall.Read(fd.sysfd, p)
		if err != nil {
			n = 0
			if err == syscall.EAGAIN {
				if err = fd.pd.waitRead(); err == nil {
					continue
				}
			}
		}
		err = fd.eofError(n, err)
		break
	}
	if _, ok := err.(syscall.Errno); ok {
		err = os.NewSyscallError("read", err)
	}
	return
}
~~~

